### ISSUE TITLE
Changing Voices

### ISSUE THREAD

**Issue by maquis** [Glutanimate/simple-google-tts#2]
Hi! 

Thanks for a great tool! I spent hours testing different solutions for my linux desktop and this is by far the best I've come accross (if you can live with sending your data to google, which ofcourse is a major drawback, but due to inavailability of free natural voice libraries and services not the fault of the author). 

I have one minor issue though: As far as I know, google tts has both mal and female voices, in some cases several of these - is there a way to change from the standard female voice for english? And if not, are you planning to include such an option in a future release?

Thanks again,
maquis

**Comment by Glutanimate** [comment]
Hi maquis,

I am glad you found this project to be useful!

Native implementations of Google TTS - such as the one in Android - do indeed offer different voices. `simple-google-tts`, however, uses Google translate to generate the actual TTS fragments. Unfortunately there's no way to change the voice output with that. Until Google decide to implement such a setting I won't be able to implement a voice selector.

Thanks for your feature request, though! I am always glad to get some feedback on my projects.
