### ISSUE TITLE
Is your script still working?

### ISSUE THREAD

**Issue by introlinux** [Glutanimate/simple-google-tts#3]
Hi, I noticed several scripts based on google tts (including yours) stopped working. Do you know why?

**Comment by Glutanimate** [comment]
It looks like Google detects scripts now and requires CAPTCHA input for every request performed by simple-google-tts. No idea how to counter this, yet. Sorry.

**Comment by Glutanimate** [comment]
Ok. This should be fixed with ca7df0dcc4e431d70d880ee5be0f8f8be14803a5.
